### ISSUE TITLE
Configure eslintrc.json to make ESLint compatible

### ISSUE THREAD

**Issue by parikhv15** [p632-sp-2016/eDocLite#21]
- Make eslint compatible with current technology stack
- Ignore files not required during linting

**Comment by jwbennet** [comment]
I would be careful here, most of the files which are generating ESLint issues should not have been checked into the project anyways so it would be better to remove them.

**Comment by parikhv15** [comment]
Yes we would make sure of  it. But right now we have 2 seperate react pages in our repository. Today we will remove one of them as only one is required.
